### ISSUE TITLE
No communication between Ableton and VLC?

### ISSUE THREAD

**Issue by GateCrasher-drummer** [ojacques/VLCMidiRemote#2]
Hello, I would kindly ask you for a help...
The goal is to play video clips from VLC playlist using Ableton MIDI track. At the moment I've VLC and Ableton on the same Windows laptop. So I've already installed rtpMIDI, so now I'm able to route the midi track in Ableton to the new output "device" created by rtpMIDI. I put note C3, then C#3 and D3 and let it looping just to test it. Then I open VLCMidiRemote, it says that a midi device was found and MIDI interface was initialized. Then I click on Start VLC, so VLC opens and my playlist appears. But that's all, it means that clips from playlist are not played or let's say only the first one is played. It seams that VLC is not receiving the instructions from Ableton. Where might be the problem? 
![ableton window](https://user-images.githubusercontent.com/39763218/40750364-4ddb66ec-6467-11e8-932b-78b3996feace.jpg)
![vlcmidiremote window](https://user-images.githubusercontent.com/39763218/40750380-5dbf60c2-6467-11e8-9100-72703a105e21.jpg)

Many thanks in advance...
Filip

**Comment by ojacques** [comment]
Filip, it seems you have everything in place for this to work. 
- rtpmidi
- the track which sends to channel 10, and notes starting with C3
- The tool which listens to channel 10

There may be an issue in VLC Midi Remote with the detection / selection of the midi device. I only used this with a remote PC, connected with Ethernet cable or Wifi/Adhoc. 

May I ask you to try with VLCMidiRemote on a remote PC with only rtpMidi as the interface?

**Comment by GateCrasher-drummer** [comment]
Solved! It works between 2 laptops! Thank you!
Now I'll try to establish the communication between a Win laptop and an iPad as I'd like to use the iPad as a VLC player device...
I have one extra question. Is there a list of VLC commands associated to midi notes? Without that, I have to try by playing different midi notes to find out the commands.  Thank you one again!

**Comment by ojacques** [comment]
Great! The midi notes will only trigger the play of an item in your playlist. So, C3 will play first video from the playlist, C#3 second, etc...
There is no start / stop / rewind, etc.
What I do is that I configure VLC to:
- Start full screen, no controls
- Pause at the end of the video

**Comment by GateCrasher-drummer** [comment]
I don't know why, but in my case the commands are shifted, it means C#2 plays the first video, D2 plays the second, etc. But it works, so I don't care. :-) Thank you indeed!
